name: NodeJS application

on:
  pull_request:
    branches: [ beta ]

jobs:
  BuildAndRun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.5.0'
    - name: Install Dependencies
      run:
        npm install
    - name: Testing Server
      run:
        npm start 
